/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;


import Model.identite;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author edmm
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
       this.setLocationRelativeTo(null);
       
       
        
        identite.alimenter_Com_adresse(com_adr);
                
       jhome.setVisible(true);
       jadr.setVisible(false);
      j1.setBackground(Color.white);
      idadr.setVisible(false);
      j_per1.setVisible(false);
      idpers.setVisible(false);
      
     
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_titre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        j1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        j2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        j3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        j4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        j5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        j6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        j7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jadr = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        prov = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comm = new javax.swing.JTextField();
        pays = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        quar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idadr = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        jhome = new javax.swing.JPanel();
        jactiv = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ja_pers = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ja_ag = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ja_fonc = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ja_comp = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        j_per1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        nomp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        prenomp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        matriculep = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cnip = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        telephonep = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        com_adr = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        idpers = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_titre.setBackground(new java.awt.Color(71, 120, 197));
        jPanel_titre.setPreferredSize(new java.awt.Dimension(1200, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        javax.swing.GroupLayout jPanel_titreLayout = new javax.swing.GroupLayout(jPanel_titre);
        jPanel_titre.setLayout(jPanel_titreLayout);
        jPanel_titreLayout.setHorizontalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titreLayout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addComponent(jLabel1)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jPanel_titreLayout.setVerticalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );

        getContentPane().add(jPanel_titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        j1.setBackground(new java.awt.Color(120, 160, 252));
        j1.setPreferredSize(new java.awt.Dimension(150, 40));
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Home");

        javax.swing.GroupLayout j1Layout = new javax.swing.GroupLayout(j1);
        j1.setLayout(j1Layout);
        j1Layout.setHorizontalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        j1Layout.setVerticalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        j2.setBackground(new java.awt.Color(120, 160, 252));
        j2.setPreferredSize(new java.awt.Dimension(150, 40));
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Adresse");

        javax.swing.GroupLayout j2Layout = new javax.swing.GroupLayout(j2);
        j2.setLayout(j2Layout);
        j2Layout.setHorizontalGroup(
            j2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        j2Layout.setVerticalGroup(
            j2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 75, -1, -1));

        j3.setBackground(new java.awt.Color(120, 160, 252));
        j3.setPreferredSize(new java.awt.Dimension(150, 40));
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Activités");

        javax.swing.GroupLayout j3Layout = new javax.swing.GroupLayout(j3);
        j3.setLayout(j3Layout);
        j3Layout.setHorizontalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        j3Layout.setVerticalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 75, -1, -1));

        j4.setBackground(new java.awt.Color(120, 160, 252));
        j4.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Colis");

        javax.swing.GroupLayout j4Layout = new javax.swing.GroupLayout(j4);
        j4.setLayout(j4Layout);
        j4Layout.setHorizontalGroup(
            j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        j4Layout.setVerticalGroup(
            j4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 75, -1, -1));

        j5.setBackground(new java.awt.Color(120, 160, 252));
        j5.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personnel");

        javax.swing.GroupLayout j5Layout = new javax.swing.GroupLayout(j5);
        j5.setLayout(j5Layout);
        j5Layout.setHorizontalGroup(
            j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
        );
        j5Layout.setVerticalGroup(
            j5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 75, -1, -1));

        j6.setBackground(new java.awt.Color(120, 160, 252));
        j6.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rapport");

        javax.swing.GroupLayout j6Layout = new javax.swing.GroupLayout(j6);
        j6.setLayout(j6Layout);
        j6Layout.setHorizontalGroup(
            j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        j6Layout.setVerticalGroup(
            j6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 75, -1, -1));

        j7.setBackground(new java.awt.Color(120, 160, 252));
        j7.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Parametre");

        javax.swing.GroupLayout j7Layout = new javax.swing.GroupLayout(j7);
        j7.setLayout(j7Layout);
        j7Layout.setHorizontalGroup(
            j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j7Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(33, 33, 33))
        );
        j7Layout.setVerticalGroup(
            j7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 75, -1, -1));

        jadr.setBackground(new java.awt.Color(204, 204, 204));
        jadr.setPreferredSize(new java.awt.Dimension(1200, 570));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prov.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel1.add(prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 202, 30));

        jLabel30.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel30.setText("Pays :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 55, 27));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel10.setText("Commune :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 27));

        comm.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel1.add(comm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 202, 30));
        jPanel1.add(pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 200, 30));

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel11.setText("Province :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 86, 27));

        quar.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel1.add(quar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 202, 30));

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel12.setText("Quartier :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 86, 27));

        idadr.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel1.add(idadr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 202, 30));

        ajouter.setBackground(new java.awt.Color(120, 160, 252));
        ajouter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel1.add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 40));

        javax.swing.GroupLayout jadrLayout = new javax.swing.GroupLayout(jadr);
        jadr.setLayout(jadrLayout);
        jadrLayout.setHorizontalGroup(
            jadrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadrLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jadrLayout.setVerticalGroup(
            jadrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadrLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jadr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jhome.setBackground(new java.awt.Color(204, 204, 204));
        jhome.setPreferredSize(new java.awt.Dimension(1200, 570));

        javax.swing.GroupLayout jhomeLayout = new javax.swing.GroupLayout(jhome);
        jhome.setLayout(jhomeLayout);
        jhomeLayout.setHorizontalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jhomeLayout.setVerticalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jactiv.setBackground(new java.awt.Color(204, 204, 204));
        jactiv.setForeground(new java.awt.Color(51, 51, 51));
        jactiv.setPreferredSize(new java.awt.Dimension(1200, 570));
        jactiv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        ja_pers.setBackground(new java.awt.Color(120, 160, 252));
        ja_pers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ja_persMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Personnel");

        javax.swing.GroupLayout ja_persLayout = new javax.swing.GroupLayout(ja_pers);
        ja_pers.setLayout(ja_persLayout);
        ja_persLayout.setHorizontalGroup(
            ja_persLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ja_persLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel9)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        ja_persLayout.setVerticalGroup(
            ja_persLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ja_persLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        ja_ag.setBackground(new java.awt.Color(120, 160, 252));
        ja_ag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ja_agMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Agence");

        javax.swing.GroupLayout ja_agLayout = new javax.swing.GroupLayout(ja_ag);
        ja_ag.setLayout(ja_agLayout);
        ja_agLayout.setHorizontalGroup(
            ja_agLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ja_agLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ja_agLayout.setVerticalGroup(
            ja_agLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ja_agLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        ja_fonc.setBackground(new java.awt.Color(120, 160, 252));
        ja_fonc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ja_foncMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Fonction");

        javax.swing.GroupLayout ja_foncLayout = new javax.swing.GroupLayout(ja_fonc);
        ja_fonc.setLayout(ja_foncLayout);
        ja_foncLayout.setHorizontalGroup(
            ja_foncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ja_foncLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ja_foncLayout.setVerticalGroup(
            ja_foncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ja_foncLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        ja_comp.setBackground(new java.awt.Color(120, 160, 252));
        ja_comp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ja_compMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Compte");

        javax.swing.GroupLayout ja_compLayout = new javax.swing.GroupLayout(ja_comp);
        ja_comp.setLayout(ja_compLayout);
        ja_compLayout.setHorizontalGroup(
            ja_compLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ja_compLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel15)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        ja_compLayout.setVerticalGroup(
            ja_compLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ja_compLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ja_fonc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ja_pers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ja_ag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ja_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ja_pers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ja_ag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ja_fonc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ja_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jactiv.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Nom :");

        nomp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Prenom :");

        prenomp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Sexe :");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Matricule :");

        matriculep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("CNI :");

        cnip.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Adresse : ");

        telephonep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton1.setText("F");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton2.setText("M");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Téléphone :");

        com_adr.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(120, 160, 252));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Add");

        idpers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout j_per1Layout = new javax.swing.GroupLayout(j_per1);
        j_per1.setLayout(j_per1Layout);
        j_per1Layout.setHorizontalGroup(
            j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_per1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_per1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(com_adr, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(j_per1Layout.createSequentialGroup()
                        .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephonep, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(j_per1Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(66, 66, 66)
                                .addComponent(jRadioButton1))
                            .addComponent(matriculep, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prenomp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cnip, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idpers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(185, 654, Short.MAX_VALUE))))
            .addGroup(j_per1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        j_per1Layout.setVerticalGroup(
            j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_per1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(idpers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_per1Layout.createSequentialGroup()
                        .addComponent(nomp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prenomp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)))
                    .addGroup(j_per1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculep, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_per1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cnip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telephonep, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(j_per1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_adr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jactiv.add(j_per1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 930, 550));

        getContentPane().add(jactiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterActionPerformed

    private void j1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseClicked
        jadr.setVisible(false);
        jhome.setVisible(true); 
        jactiv.setVisible(false);
        j1.setBackground(Color.white);
        j2.setBackground(new Color(120,160,252));
        j3.setBackground(new Color(120,160,252));
          
        
    }//GEN-LAST:event_j1MouseClicked

    private void j2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseClicked
      jadr.setVisible(true);
        jhome.setVisible(false);
        jactiv.setVisible(false);
        j2.setBackground(Color.white);
      j1.setBackground(new Color(120,160,252));
      j3.setBackground(new Color(120,160,252));
       
        
        Border men = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        j1.setBorder(men);
    }//GEN-LAST:event_j2MouseClicked

    private void j3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseClicked
        
        jadr.setVisible(false);
        jhome.setVisible(false); 
        jactiv.setVisible(true);
        j3.setBackground(Color.white);
        j2.setBackground(new Color(120,160,252));
        j1.setBackground(new Color(120,160,252));
        ja_pers.setBackground(new Color(255,255,255));
        ja_ag.setBackground(new Color(120,160,252));
        ja_comp.setBackground(new Color(120,160,252));
        ja_fonc.setBackground(new Color(120,160,252));
        j_per1.setVisible(true);
    }//GEN-LAST:event_j3MouseClicked

    private void ja_persMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ja_persMouseClicked

        ja_pers.setBackground(Color.white);
        ja_ag.setBackground(new Color(120,160,252));
        ja_fonc.setBackground(new Color(120,160,252));
        ja_comp.setBackground(new Color(120,160,252));
        
       j_per1.setVisible(true);
    }//GEN-LAST:event_ja_persMouseClicked

    private void ja_agMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ja_agMouseClicked
       ja_ag.setBackground(Color.white);
        ja_pers.setBackground(new Color(120,160,252));
        ja_fonc.setBackground(new Color(120,160,252));
        ja_comp.setBackground(new Color(120,160,252));
    }//GEN-LAST:event_ja_agMouseClicked

    private void ja_foncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ja_foncMouseClicked
        ja_fonc.setBackground(Color.white);
        ja_ag.setBackground(new Color(120,160,252));
        ja_pers.setBackground(new Color(120,160,252));
        ja_comp.setBackground(new Color(120,160,252));
    }//GEN-LAST:event_ja_foncMouseClicked

    private void ja_compMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ja_compMouseClicked
        ja_comp.setBackground(Color.white);
        ja_ag.setBackground(new Color(120,160,252));
        ja_fonc.setBackground(new Color(120,160,252));
        ja_pers.setBackground(new Color(120,160,252));
    }//GEN-LAST:event_ja_compMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
        
        
    }

    public JTextField getComm() {
        return comm;
    }

    public void setComm(JTextField comm) {
        this.comm = comm;
    }

    public JTextField getIdadr() {
        return idadr;
    }

    public void setIdadr(JTextField idadr) {
        this.idadr = idadr;
    }

    public JTextField getPays() {
        return pays;
    }

    public void setPays(JTextField pays) {
        this.pays = pays;
    }

    public JTextField getProv() {
        return prov;
    }

    public void setProv(JTextField prov) {
        this.prov = prov;
    }

    public JTextField getQuar() {
        return quar;
    }

    public void setQuar(JTextField quar) {
        this.quar = quar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JTextField cnip;
    private javax.swing.JComboBox com_adr;
    private javax.swing.JTextField comm;
    private javax.swing.JTextField idadr;
    private javax.swing.JTextField idpers;
    private javax.swing.JPanel j1;
    private javax.swing.JPanel j2;
    private javax.swing.JPanel j3;
    private javax.swing.JPanel j4;
    private javax.swing.JPanel j5;
    private javax.swing.JPanel j6;
    private javax.swing.JPanel j7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_titre;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel j_per1;
    private javax.swing.JPanel ja_ag;
    private javax.swing.JPanel ja_comp;
    private javax.swing.JPanel ja_fonc;
    private javax.swing.JPanel ja_pers;
    private javax.swing.JPanel jactiv;
    private javax.swing.JPanel jadr;
    private javax.swing.JPanel jhome;
    private javax.swing.JTextField matriculep;
    private javax.swing.JTextField nomp;
    private javax.swing.JTextField pays;
    private javax.swing.JTextField prenomp;
    private javax.swing.JTextField prov;
    private javax.swing.JTextField quar;
    private javax.swing.JTextField telephonep;
    // End of variables declaration//GEN-END:variables
}
